language: android
android:
  components:
    - build-tools-28.0.0
    - android-28
    # - add-on
    - extra
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-28